/*
 * This source file was generated by the Gradle 'init' task
 */
package project_1;

public class App {
    public String alterPayload(String Payload){
        System.out.println("let's check");
        return Payload.toLowerCase().replace('e','3').replace('i','1');
    }

}
